guild = 842778964673953812

[roles.mentionable]
general_announcements = 1073292414271356938
website_patch_notes = 1328055776358563990
framework_patch_notes = 1073292274877878314
modmail = 1120076555293569081

[roles.location]
south_america = 1073285860239360060
oceana = 1073285809505046699
north_america = 1072934825981386893
europe = 1072934890032615445
asia = 1072934956227100803
africa = 1073285906422845600

[roles.platform]
console = 1072935043766427718
pc = 1072935061202141204

[roles.misc]
tag_maker = 1072935381357576334
developer = 1072933188378308750
mapmaker = 1001688523067371582

[roles.admin]
mod = 1128014001318666423
sensei = 842790097312153610
dev = 1140642981548937226
joe = 1128014370396442645

[channels.updates]
announcements = 975820285343301674
newsfeed = 1072897578762506260
xp = 1324496532447166505
editor_patch_notes = 844981073050206219
website_patch_notes = 1328055284555321354
dlq_alerts = 1435317782815182960

[channels.information]
rank_promotion = 853278414134575104
map_submission_info = 1073317281704189973
website_info = 1326941138057429083
xp_info = 1326941087767462009
role_react = 1072897860544241804

[channels.submission]
completions = 1072898844339224627
playtest = 1369672124352040970
verification_queue = 1072898747551469658
upvotes = 1435318635101945898

[channels.help]
ask_for_help = 974034121456234578
modmail = 1120029553998450719
suggestions_and_bug_reports = 945766151714131970
change_requests = 1342953312000934069

[channels.admin]
development = 999420219900571658
round_table = 858150590659821598
